version: "3.7"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb
    build: ./
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./data:/data
    networks:
      - sam-ddb
networks:
  sam-ddb:
    external: true